// Generated by binding-generator from mcp-core types
// Build fingerprint: 6f2d331-20250807172413
// Generated at: 2025-08-07T17:24:13.965312+00:00
// NO MOCK FUNCTIONS - Direct type extraction!


// Core types from mcp-core
export interface ModelInfo {
    id: string;
    display_name: string;
    organization: string;
}

export interface ApiError {
    message: string;
    code?: string;
}

export interface ChatStreamPayload {
    content: string;
}

export interface ChatErrorPayload {
    error: string;
}

export interface BuildInfo {
    module: string;
    fingerprint: string;
    git_commit: string;
    git_headline: string;
    build_time: string;
    dependencies: DependencyInfo[];
}

export interface DependencyInfo {
    module: string;
    fingerprint: string;
    verified: boolean;
}

export type StreamMessage = 
    | { Content: string }
    | { Error: string }
    | "Complete";

// Command return types (all commands return Result<T, String>)
export type ApiResult<T> = { Ok: T } | { Err: string };
