// Generated by binding-generator from mcp-core types
// Build fingerprint: 99417c1e3ff2a24e16b4731a478d32e46dcbfcddf9655798519a47602234d6b3
// Generated at: 2025-08-08T05:05:07.425029+00:00
// NO MOCK FUNCTIONS - Direct type extraction!

// AUTOMATICALLY GENERATED FROM RUST TYPES - DO NOT EDIT
// Generated using ts-rs type extraction

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
export type ModelInfo = { id: string, display_name: string, organization: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
export type ApiError = { message: string, code: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
export type StreamMessage = { "Content": string } | { "Error": string } | "Complete";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
export type ChatStreamPayload = { content: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
export type ChatErrorPayload = { error: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
export type DependencyInfo = { module: string, fingerprint: string, verified: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
/**
 * Build information with embedded constants generated at compile time
 */
export type BuildInfo = { module: string, fingerprint: string, git_commit: string, git_headline: string, build_time: string, dependencies: Array<DependencyInfo>, };

// Command return types (all commands return Result<T, String>)
export type ApiResult<T> = { Ok: T } | { Err: string };
