// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependencyInfo } from "./DependencyInfo";

/**
 * Build information with embedded constants generated at compile time
 */
export type BuildInfo = { module: string, fingerprint: string, git_commit: string, git_headline: string, build_time: string, dependencies: Array<DependencyInfo>, };
